/* MCI - INTEGRAL CONSCIOUSNESS METHODOLOGY - SILVER DATASET EN */
const mciContent = [
    { q: "I am the master of my inner peace.", a: "Observe your thoughts without judgment today." },
    { q: "My energy creates my reality.", a: "Focus on one positive thing today, no matter how small." },
    { q: "Every breath is a new beginning.", a: "Take 3 deep breaths before answering any message." },
    { q: "Gratitude turns what we have into enough.", a: "Write down 3 things you are grateful for today." },
    { q: "I release what I cannot control.", a: "Focus only on your current step." },
    { q: "Self-care is essential for my evolution.", a: "Dedicate 15 minutes to yourself today." },
    { q: "My body is my temple.", a: "Stretch and feel the life in your muscles." },
    { q: "I listen to the wisdom of my heart.", a: "Silence is where the true answers live." },
    { q: "Challenges are opportunities for growth.", a: "See the lesson in every difficulty today." },
    { q: "I am worthy of all the good life offers.", a: "Open your heart to receive abundance." },
    { q: "I am present in the here and now.", a: "Focus 100% on what you are doing in this moment." },
    { q: "Consistency leads to transformation.", a: "Keep your MCI practice alive today." },
    { q: "I choose thoughts that empower me.", a: "Replace one negative thought with a powerful one." },
    { q: "Silence is my source of clarity.", a: "Find 5 minutes of absolute silence today." },
    { q: "I am connected to the whole universe.", a: "Look at the sky and feel the vastness." },
    { q: "Forgiveness sets my soul free.", a: "Release a grudge you have been carrying." },
    { q: "My potential is truly infinite.", a: "Try a new way of doing a routine task." },
    { q: "I act with clear intention.", a: "Define your 'why' before starting a project." },
    { q: "Patience is trusting the divine process.", a: "Breathe deeply when you feel in a hurry." },
    { q: "I celebrate my progress every day.", a: "Acknowledge how far you have already come." },
    { q: "Love is the highest frequency.", a: "Send a loving thought to someone you dislike." },
    { q: "I am a beacon of light for others.", a: "Give a sincere compliment today." },
    { q: "Balance is my foundation.", a: "Balance work with a moment of real rest." },
    { q: "I am open to the wonders of life.", a: "Expect a positive surprise today." },
    { q: "My word is my bond with reality.", a: "Speak only what you intend to create." },
    { q: "Intuition is my internal guide.", a: "Listen to that quiet voice in your gut." },
    { q: "I let go of the past completely.", a: "Organize one small space to clear your energy." },
    { q: "Harmony begins deep within me.", a: "Listen to peaceful music for 10 minutes." },
    { q: "I am resilient and powerful.", a: "Remember a victory from your past." },
    { q: "Every day is a gift of consciousness.", a: "Smile at your reflection today." },
    { q: "I am an integral being in evolution.", a: "Reflect on one lesson learned today." },
    { q: "Abundance is my natural state.", a: "Count 5 things you have that money can't buy." },
    { q: "I trust the timing of my life.", a: "Stop rushing and trust the flow." },
    { q: "I am the creator of my joy.", a: "Do something that makes you laugh today." },
    { q: "My silence is full of power.", a: "Listen more than you speak today." },
    { q: "I radiate peace and love.", a: "Visualize light around you when walking." },
    { q: "I am bold in my pursuit of truth.", a: "Ask yourself a hard question and be honest." },
    { q: "My vibration is rising.", a: "Avoid gossip and negative news today." },
    { q: "I am a master of my emotions.", a: "Observe an emotion without reacting to it." },
    { q: "I am grateful for my journey.", a: "Thank the universe for being alive today." }
];
